In [1]:
#importing the required modules
import glob
import pandas as pd

In [2]:
#raw data folder paths
rawDataPath = "C:\\Users\\Chefo\\Documents\\SapRawData"

# file path list using glob
file_list = glob.glob(rawDataPath + "\\*.xlsx")

In [3]:
#df1Path ="C:\\Users\\Chefo\\Documents\\SapRawData\\26TH AUG HALF.xlsx"
#df1=pd.read_excel(df1Path)

#print(df1.shape)

In [4]:
# we list the excel file we want to merge
excl_list = []

#we read the files using pd.read and for loop 
# the we append it to the excl_list

for file in file_list:
    excl_list.append(pd.read_excel(file))

In [5]:
excl_merged = pd.concat(excl_list, ignore_index=True)
print(excl_merged.shape)

(3633, 38)

In [6]:
# we create an empty dataframe to store the merged excel file
#excl_merged = pd.DataFrame()

#we loop through our excel list and append to excl_merge
#for excl_file in excl_list:
    #excl_merged = excl_merged.append(excl_file, ignore_index = True)
#print(excl_merged.shape)

In [7]:
excl_merged

,Delivery NO,Delv Doc Type,Parent SO,Sales Doc Number,Sales Doc Type,Customer No,Customer Name,Dispatch Plant,Shipping Point,Material,...,Sales Officer,Sales Manager,Regional Director,Mov.Type,Profit Center,Risk Category,TotalGdsMvtStat,Bill.stat.order,Ovr.pick.status,Invoice No
0,0205781057,NL,NaN,4800039091,NaN,0000005092,DEPOT - ASABA VIRTUAL,1100,1101,BAGBM_OBA_1100,...,NaN,JIDE ARE,GEORGE OKORO,641,1120,NaN,C,NaN,C,NaN
1,0205781058,NL,NaN,4800039091,NaN,0000005092,DEPOT - ASABA VIRTUAL,1100,1101,BAGBM_OBA_1100,...,NaN,JIDE ARE,GEORGE OKORO,641,1120,NaN,C,NaN,C,NaN
2,0205781059,NL,NaN,4800039091,NaN,0000005092,DEPOT - ASABA VIRTUAL,1100,1101,BAGBM_OBA_1100,...,NaN,JIDE ARE,GEORGE OKORO,641,1120,NaN,C,NaN,C,NaN
3,0205781060,NL,NaN,4800039091,NaN,0000005092,DEPOT - ASABA VIRTUAL,1100,1101,BAGBM_OBA_1100,...,NaN,JIDE ARE,GEORGE OKORO,641,1120,NaN,C,NaN,C,NaN
4,0205810095,NL,NaN,NG30005605,NaN,0000005012,Depot-BENIN,1100,1101,BAG2N_OBA_1100,...,NaN,SABITU MAHAMMED,ABAYOMI SHITTU,641,1120,NaN,C,NaN,C,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3628,OK00008889,ZLF,1.201452e+07,5300128510,YSOR,0001009775,DIVINE CONSENT INTERNATIONAL,1022,OKP1,BAG2N_OKP_1021,...,NaN,JOHNSON ISOGIE,BANKOLE GEORGE,601,1022,101.0,C,C,C,325091075.0
3629,OK00008890,ZLF,5.300128e+09,0116009874,YSOR,0001023338,YOLUCHUKWU MULTI - BIZ ENTERPRISE,1022,OKP1,BAG2N_OKP_1021,...,NaN,MUSTAPHA YELWA,DOLAPO ALLI,601,1022,101.0,C,C,C,325091076.0
3630,OK00008891,ZLF,4.201443e+07,0088020340,YSOR,0001009838,CYPRESS CAPITAL NIG. LTD.,1022,OKP1,BAG2N_OKP_1021,...,NaN,MUSTAPHA YELWA,DOLAPO ALLI,601,1022,101.0,C,C,C,325091077.0
3631,OK00008892,ZLF,4.201443e+07,2042013047,YSOR,0001009838,CYPRESS CAPITAL NIG. LTD.,1022,OKP1,BAG2N_OKP_1021,...,NaN,MUSTAPHA YELWA,DOLAPO ALLI,601,1022,101.0,C,C,C,325091078.0
3632,OK00008893,ZLF,5.300127e+09,0196016256,YSOR,0001002153,JOJA-ZEMA NIG LTD,1022,OKP1,BAG2N_OKP_1021,...,NaN,ADESANYA MUYIWA,BANKOLE GEORGE,601,1022,101.0,C,C,C,325091079.0

In [8]:
print(excl_merged.shape)

(3633, 38)

In [9]:
# exports the dataframe into csv file and is named MergedSap.
excl_merged.to_csv('MergedSap.csv', index=False)